-include .env

.PHONY: clean remove deploy deploy-goerli deploy-sepolia

DEFAULT_ANVIL_KEY := 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

# Clean repo
clean  :; forge clean

# Remove modules
remove :; rm -rf .gitmodules && rm -rf .git/modules/* && rm -rf lib && touch .gitmodules && git add . && git commit -m "modules"

deploy: 
	@forge script script/DeployBountyFactory.s.sol:DeployBountyFactory --rpc-url http://localhost:8545 --private-key $(DEFAULT_ANVIL_KEY) --broadcast

deploy-goerli:
	@forge script script/DeployBountyFactory.s.sol:DeployBountyFactory --rpc-url $(GOERLI_RPC_URL) --private-key $(PRIVATE_KEY) --broadcast --verify --etherscan-api-key $(ETHERSCAN_API_KEY) -vvvv

deploy-polygon-mumbai:
	@forge script script/DeployBountyFactory.s.sol:DeployBountyFactory --rpc-url $(POLYGON_MUMBAI_RPC_URL) --private-key $(PRIVATE_KEY) --broadcast --verify --etherscan-api-key $(POLYGONSCAN_API_KEY) -vvvv

deploy-scroll-sepolia:
	@forge script script/DeployBountyFactory.s.sol:DeployBountyFactory --rpc-url $(SCROLL_SEPOLIA_RPC_URL) --legacy --private-key $(PRIVATE_KEY) --broadcast

deploy-mantle-testnet:
	@forge script script/DeployBountyFactory.s.sol:DeployBountyFactory --rpc-url $(MANTLE_TESTNET_RPC_URL) --legacy --private-key $(PRIVATE_KEY) --broadcast

